<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="1" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[The Element is present]]>
    </line>
    <line>
      <![CDATA[The Element is not present]]>
    </line>
    <line>
      <![CDATA[The Element is present]]>
    </line>
    <line>
      <![CDATA[The Element is not present]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="38414" started-at="2018-03-16T13:37:40Z" finished-at="2018-03-16T13:38:19Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="38414" started-at="2018-03-16T13:37:40Z" finished-at="2018-03-16T13:38:19Z">
      <class name="scripts.FistTimeRegistrationHomePage">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:scripts.FistTimeRegistrationHomePage@5bcab519]" name="openApplication" is-config="true" duration-ms="22801" started-at="2018-03-16T13:37:54Z" finished-at="2018-03-16T13:38:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="fisrtlogin()[pri:2, instance:scripts.FistTimeRegistrationHomePage@5bcab519]" name="fisrtlogin" duration-ms="1585" started-at="2018-03-16T13:38:17Z" finished-at="2018-03-16T13:38:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at generic.Base_Page.elementIsPresent(Base_Page.java:46)
at pom.First_Time_Login_HomePage.verifyhomeFirst(First_Time_Login_HomePage.java:41)
at scripts.FistTimeRegistrationHomePage.fisrtlogin(FistTimeRegistrationHomePage.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[The Element is present]]>
            </line>
            <line>
              <![CDATA[The Element is not present]]>
            </line>
          </reporter-output>
        </test-method> <!-- fisrtlogin -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:scripts.FistTimeRegistrationHomePage@5bcab519]" name="closeApp" is-config="true" duration-ms="385" started-at="2018-03-16T13:38:18Z" finished-at="2018-03-16T13:38:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- scripts.FistTimeRegistrationHomePage -->
      <class name="script_FistTimeLogin.FistTimeRegistrationHomePage">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:script_FistTimeLogin.FistTimeRegistrationHomePage@31a5c39e]" name="openApplication" is-config="true" duration-ms="11414" started-at="2018-03-16T13:37:40Z" finished-at="2018-03-16T13:37:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="fisrtlogin()[pri:2, instance:script_FistTimeLogin.FistTimeRegistrationHomePage@31a5c39e]" name="fisrtlogin" duration-ms="1773" started-at="2018-03-16T13:37:52Z" finished-at="2018-03-16T13:37:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at generic.Base_Page.elementIsPresent(Base_Page.java:46)
at pom.First_Time_Login_HomePage.verifyhomeFirst(First_Time_Login_HomePage.java:41)
at script_FistTimeLogin.FistTimeRegistrationHomePage.fisrtlogin(FistTimeRegistrationHomePage.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[The Element is present]]>
            </line>
            <line>
              <![CDATA[The Element is not present]]>
            </line>
          </reporter-output>
        </test-method> <!-- fisrtlogin -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:script_FistTimeLogin.FistTimeRegistrationHomePage@31a5c39e]" name="closeApp" is-config="true" duration-ms="397" started-at="2018-03-16T13:37:53Z" finished-at="2018-03-16T13:37:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script_FistTimeLogin.FistTimeRegistrationHomePage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
